name: Run Karate Tests

on: [push]

jobs:
  karate-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
        cache: 'maven'
        cache-dependency-path: '**/pom.xml'

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with:
        files: |
          target/surefire-reports/*.xml
          target/karate-reports/karate-summary.html
        comment_title: Test Results for Karate Tests