name: Run Karate Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  karate-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
        cache: 'maven'
        cache-dependency-path: '**/pom.xml'

    - name: Build and Run Tests with Maven
      run: mvn clean test